services:
  - type: web
    name: codely-dev
    runtime: node
    plan: free
    buildCommand: npm install && npm --prefix client install --include=dev && npm --prefix server install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: GEMINI_API_KEY
        sync: false
