export const CUSTOM_THEMES = {
  'dracula': {
    base: 'vs-dark',
    inherit: true,
    rules: [
      { background: '282a36' },
      { token: '', foreground: 'f8f8f2', background: '282a36' },
      { token: 'comment', foreground: '6272a4' },
      { token: 'string', foreground: 'f1fa8c' },
      { token: 'keyword', foreground: 'ff79c6' },
      { token: 'number', foreground: 'bd93f9' },
      { token: 'type', foreground: '8be9fd', fontStyle: 'italic' },
      { token: 'class', foreground: '50fa7b' },
      { token: 'function', foreground: '50fa7b' },
      { token: 'variable', foreground: 'f8f8f2' },
      { token: 'constant', foreground: 'bd93f9' },
      { token: 'operator', foreground: 'ff79c6' },
    ],
    colors: {
      'editor.background': '#282a36',
      'editor.foreground': '#f8f8f2',
      'editor.selectionBackground': '#44475a',
      'editor.lineHighlightBackground': '#44475a55',
      'editorCursor.foreground': '#f8f8f0',
      'editorWhitespace.foreground': '#3B3A32',
      'editorIndentGuide.background': '#9D550FB0',
      'editorIndentGuide.activeBackground': '#9D550F',
    }
  },
  'nord': {
    base: 'vs-dark',
    inherit: true,
    rules: [
      { background: '2E3440' },
      { token: '', foreground: 'D8DEE9', background: '2E3440' },
      { token: 'comment', foreground: '4C566A' },
      { token: 'string', foreground: 'A3BE8C' },
      { token: 'keyword', foreground: '81A1C1' },
      { token: 'number', foreground: 'B48EAD' },
      { token: 'type', foreground: '8FBCBB' },
      { token: 'class', foreground: '8FBCBB' },
      { token: 'function', foreground: '88C0D0' },
      { token: 'variable', foreground: 'D8DEE9' },
      { token: 'constant', foreground: 'D08770' },
      { token: 'operator', foreground: '81A1C1' },
    ],
    colors: {
      'editor.background': '#2E3440',
      'editor.foreground': '#D8DEE9',
      'editor.selectionBackground': '#434C5E',
      'editor.lineHighlightBackground': '#3B4252',
      'editorCursor.foreground': '#D8DEE9',
    }
  },
  'night-owl': {
    base: 'vs-dark',
    inherit: true,
    rules: [
      { background: '011627' },
      { token: '', foreground: 'd6deeb', background: '011627' },
      { token: 'comment', foreground: '637777', fontStyle: 'italic' },
      { token: 'string', foreground: 'ecc48d' },
      { token: 'keyword', foreground: 'c792ea', fontStyle: 'italic' },
      { token: 'number', foreground: 'f78c6c' },
      { token: 'type', foreground: 'addb67' },
      { token: 'class', foreground: 'ffcb8b' },
      { token: 'function', foreground: '82aaff' },
      { token: 'variable', foreground: 'd6deeb' },
      { token: 'constant', foreground: '82aaff' },
      { token: 'operator', foreground: 'c792ea' },
    ],
    colors: {
      'editor.background': '#011627',
      'editor.foreground': '#d6deeb',
      'editor.selectionBackground': '#1d3b53',
      'editor.lineHighlightBackground': '#1d3b5333',
      'editorCursor.foreground': '#80a4c2',
    }
  },
  'github-dark': {
    base: 'vs-dark',
    inherit: true,
    rules: [
      { background: '0d1117' },
      { token: '', foreground: 'c9d1d9', background: '0d1117' },
      { token: 'comment', foreground: '8b949e' },
      { token: 'string', foreground: 'a5d6ff' },
      { token: 'keyword', foreground: 'ff7b72' },
      { token: 'number', foreground: '79c0ff' },
      { token: 'type', foreground: 'ff7b72' },
      { token: 'class', foreground: 'f0883e' },
      { token: 'function', foreground: 'd2a8ff' },
      { token: 'variable', foreground: 'c9d1d9' },
      { token: 'constant', foreground: '79c0ff' },
      { token: 'operator', foreground: 'c9d1d9' },
    ],
    colors: {
      'editor.background': '#0d1117',
      'editor.foreground': '#c9d1d9',
      'editor.selectionBackground': '#3392FF44',
      'editor.lineHighlightBackground': '#161b22',
      'editorCursor.foreground': '#c9d1d9',
    }
  },
  'github-light': {
    base: 'vs',
    inherit: true,
    rules: [
      { background: 'ffffff' },
      { token: '', foreground: '24292e', background: 'ffffff' },
      { token: 'comment', foreground: '6a737d' },
      { token: 'string', foreground: '032f62' },
      { token: 'keyword', foreground: 'd73a49' },
      { token: 'number', foreground: '005cc5' },
      { token: 'type', foreground: 'd73a49' },
      { token: 'class', foreground: '6f42c1' },
      { token: 'function', foreground: '6f42c1' },
      { token: 'variable', foreground: '24292e' },
      { token: 'constant', foreground: '005cc5' },
      { token: 'operator', foreground: 'd73a49' },
    ],
    colors: {
      'editor.background': '#ffffff',
      'editor.foreground': '#24292e',
      'editor.selectionBackground': '#0366d625',
      'editor.lineHighlightBackground': '#f6f8fa',
      'editorCursor.foreground': '#24292e',
    }
  }
};

export const THEME_OPTIONS = [
  { value: 'vs-dark', label: 'VS Dark (Default)', type: 'dark', hex: '#1e1e1e' },
  { value: 'github-dark', label: 'GitHub Dark', type: 'dark', hex: '#0d1117' },
  { value: 'dracula', label: 'Dracula', type: 'dark', hex: '#282a36' },
  { value: 'nord', label: 'Nord', type: 'dark', hex: '#2E3440' },
  { value: 'night-owl', label: 'Night Owl', type: 'dark', hex: '#011627' },
  { value: 'vs', label: 'VS Light', type: 'light', hex: '#ffffff' },
  { value: 'github-light', label: 'GitHub Light', type: 'light', hex: '#ffffff' },
];
