export const CUSTOM_THEMES = {
  'dracula': {
    base: 'vs-dark',
    inherit: true,
    rules: [
      { background: '282a36' },
      { token: '', foreground: 'f8f8f2', background: '282a36' },
      { token: 'comment', foreground: '6272a4' },
      { token: 'string', foreground: 'f1fa8c' },
      { token: 'keyword', foreground: 'ff79c6' },
      { token: 'number', foreground: 'bd93f9' },
      { token: 'type', foreground: '8be9fd', fontStyle: 'italic' },
      { token: 'class', foreground: '50fa7b' },
      { token: 'function', foreground: '50fa7b' },
      { token: 'variable', foreground: 'f8f8f2' },
      { token: 'constant', foreground: 'bd93f9' },
      { token: 'operator', foreground: 'ff79c6' },
    ],
    colors: {
      'editor.background': '#282a36',
      'editor.foreground': '#f8f8f2',
      'editor.selectionBackground': '#44475a',
      'editor.lineHighlightBackground': '#44475a55',
      'editorCursor.foreground': '#f8f8f0',
      'editorWhitespace.foreground': '#3B3A32',
      'editorIndentGuide.background': '#9D550FB0',
      'editorIndentGuide.activeBackground': '#9D550F',
    }
  },
  'nord': {
    base: 'vs-dark',
    inherit: true,
    rules: [
      { background: '2E3440' },
      { token: '', foreground: 'D8DEE9', background: '2E3440' },
      { token: 'comment', foreground: '4C566A' },
      { token: 'string', foreground: 'A3BE8C' },
      { token: 'keyword', foreground: '81A1C1' },
      { token: 'number', foreground: 'B48EAD' },
      { token: 'type', foreground: '8FBCBB' },
      { token: 'class', foreground: '8FBCBB' },
      { token: 'function', foreground: '88C0D0' },
      { token: 'variable', foreground: 'D8DEE9' },
      { token: 'constant', foreground: 'D08770' },
      { token: 'operator', foreground: '81A1C1' },
    ],
    colors: {
      'editor.background': '#2E3440',
      'editor.foreground': '#D8DEE9',
      'editor.selectionBackground': '#434C5E',
      'editor.lineHighlightBackground': '#3B4252',
      'editorCursor.foreground': '#D8DEE9',
    }
  },
  'night-owl': {
    base: 'vs-dark',
    inherit: true,
    rules: [
      { background: '011627' },
      { token: '', foreground: 'd6deeb', background: '011627' },
      { token: 'comment', foreground: '637777', fontStyle: 'italic' },
      { token: 'string', foreground: 'ecc48d' },
      { token: 'keyword', foreground: 'c792ea', fontStyle: 'italic' },
      { token: 'number', foreground: 'f78c6c' },
      { token: 'type', foreground: 'addb67' },
      { token: 'class', foreground: 'ffcb8b' },
      { token: 'function', foreground: '82aaff' },
      { token: 'variable', foreground: 'd6deeb' },
      { token: 'constant', foreground: '82aaff' },
      { token: 'operator', foreground: 'c792ea' },
    ],
    colors: {
      'editor.background': '#011627',
      'editor.foreground': '#d6deeb',
      'editor.selectionBackground': '#1d3b53',
      'editor.lineHighlightBackground': '#1d3b5333',
      'editorCursor.foreground': '#80a4c2',
    }
  },
  'github-dark': {
    base: 'vs-dark',
    inherit: true,
    rules: [
      { background: '0d1117' },
      { token: '', foreground: 'c9d1d9', background: '0d1117' },
      { token: 'comment', foreground: '8b949e' },
      { token: 'string', foreground: 'a5d6ff' },
      { token: 'keyword', foreground: 'ff7b72' },
      { token: 'number', foreground: '79c0ff' },
      { token: 'type', foreground: 'ff7b72' },
      { token: 'class', foreground: 'f0883e' },
      { token: 'function', foreground: 'd2a8ff' },
      { token: 'variable', foreground: 'c9d1d9' },
      { token: 'constant', foreground: '79c0ff' },
      { token: 'operator', foreground: 'c9d1d9' },
    ],
    colors: {
      'editor.background': '#0d1117',
      'editor.foreground': '#c9d1d9',
      'editor.selectionBackground': '#3392FF44',
      'editor.lineHighlightBackground': '#161b22',
      'editorCursor.foreground': '#c9d1d9',
    }
  },
  'github-light': {
    base: 'vs',
    inherit: true,
    rules: [
      { background: 'ffffff' },
      { token: '', foreground: '24292e', background: 'ffffff' },
      { token: 'comment', foreground: '6a737d' },
      { token: 'string', foreground: '032f62' },
      { token: 'keyword', foreground: 'd73a49' },
      { token: 'number', foreground: '005cc5' },
      { token: 'type', foreground: 'd73a49' },
      { token: 'class', foreground: '6f42c1' },
      { token: 'function', foreground: '6f42c1' },
      { token: 'variable', foreground: '24292e' },
      { token: 'constant', foreground: '005cc5' },
      { token: 'operator', foreground: 'd73a49' },
    ],
    colors: {
      'editor.background': '#ffffff',
      'editor.foreground': '#24292e',
      'editor.selectionBackground': '#0366d625',
      'editor.lineHighlightBackground': '#f6f8fa',
      'editorCursor.foreground': '#24292e',
    }
  },
  'monokai': {
    base: 'vs-dark',
    inherit: true,
    rules: [
      { background: '272822' },
      { token: '', foreground: 'f8f8f2', background: '272822' },
      { token: 'comment', foreground: '75715e' },
      { token: 'string', foreground: 'e6db74' },
      { token: 'keyword', foreground: 'f92672' },
      { token: 'number', foreground: 'ae81ff' },
      { token: 'type', foreground: '66d9ef', fontStyle: 'italic' },
      { token: 'class', foreground: 'a6e22e' },
      { token: 'function', foreground: 'a6e22e' },
      { token: 'variable', foreground: 'f8f8f2' },
      { token: 'constant', foreground: 'ae81ff' },
      { token: 'operator', foreground: 'f92672' },
    ],
    colors: {
      'editor.background': '#272822',
      'editor.foreground': '#f8f8f2',
      'editor.selectionBackground': '#49483E',
      'editor.lineHighlightBackground': '#3E3D32',
      'editorCursor.foreground': '#f8f8f0',
    }
  },
  'synthwave84': {
    base: 'vs-dark',
    inherit: true,
    rules: [
      { background: '262335' },
      { token: '', foreground: 'f92aad', background: '262335' },
      { token: 'comment', foreground: '848bbd', fontStyle: 'italic' },
      { token: 'string', foreground: 'ff8b39' },
      { token: 'keyword', foreground: 'f92aad' },
      { token: 'number', foreground: 'f97e72' },
      { token: 'type', foreground: 'fdfdfd' },
      { token: 'class', foreground: 'fdfdfd' },
      { token: 'function', foreground: '36f9f6' },
      { token: 'variable', foreground: 'ff7edb' },
      { token: 'constant', foreground: 'f92aad' },
      { token: 'operator', foreground: 'f92aad' },
    ],
    colors: {
      'editor.background': '#262335',
      'editor.foreground': '#ff7edb',
      'editor.selectionBackground': '#ffffff20',
      'editor.lineHighlightBackground': '#ffffff0d',
      'editorCursor.foreground': '#f92aad',
    }
  },
  'one-dark-pro': {
    base: 'vs-dark',
    inherit: true,
    rules: [
      { background: '282c34' },
      { token: '', foreground: 'abb2bf', background: '282c34' },
      { token: 'comment', foreground: '5c6370', fontStyle: 'italic' },
      { token: 'string', foreground: '98c379' },
      { token: 'keyword', foreground: 'c678dd' },
      { token: 'number', foreground: 'd19a66' },
      { token: 'type', foreground: 'e5c07b' },
      { token: 'class', foreground: 'e5c07b' },
      { token: 'function', foreground: '61afef' },
      { token: 'variable', foreground: 'e06c75' },
      { token: 'constant', foreground: 'd19a66' },
      { token: 'operator', foreground: '56b6c2' },
    ],
    colors: {
      'editor.background': '#282c34',
      'editor.foreground': '#abb2bf',
      'editor.selectionBackground': '#3e4451',
      'editor.lineHighlightBackground': '#2c313c',
      'editorCursor.foreground': '#528bff',
    }
  },
  'solarized-dark': {
    base: 'vs-dark',
    inherit: true,
    rules: [
      { background: '002b36' },
      { token: '', foreground: '839496', background: '002b36' },
      { token: 'comment', foreground: '586e75', fontStyle: 'italic' },
      { token: 'string', foreground: '2aa198' },
      { token: 'keyword', foreground: '859900' },
      { token: 'number', foreground: 'd33682' },
      { token: 'type', foreground: 'b58900' },
      { token: 'class', foreground: 'b58900' },
      { token: 'function', foreground: '268bd2' },
      { token: 'variable', foreground: '268bd2' },
      { token: 'constant', foreground: 'cb4b16' },
      { token: 'operator', foreground: '859900' },
    ],
    colors: {
      'editor.background': '#002b36',
      'editor.foreground': '#839496',
      'editor.selectionBackground': '#073642',
      'editor.lineHighlightBackground': '#073642',
      'editorCursor.foreground': '#d33682',
    }
  },
  'solarized-light': {
    base: 'vs',
    inherit: true,
    rules: [
      { background: 'fdf6e3' },
      { token: '', foreground: '657b83', background: 'fdf6e3' },
      { token: 'comment', foreground: '93a1a1', fontStyle: 'italic' },
      { token: 'string', foreground: '2aa198' },
      { token: 'keyword', foreground: '859900' },
      { token: 'number', foreground: 'd33682' },
      { token: 'type', foreground: 'b58900' },
      { token: 'class', foreground: 'b58900' },
      { token: 'function', foreground: '268bd2' },
      { token: 'variable', foreground: '268bd2' },
      { token: 'constant', foreground: 'cb4b16' },
      { token: 'operator', foreground: '859900' },
    ],
    colors: {
      'editor.background': '#fdf6e3',
      'editor.foreground': '#657b83',
      'editor.selectionBackground': '#eee8d5',
      'editor.lineHighlightBackground': '#eee8d5',
      'editorCursor.foreground': '#657b83',
    }
  },
  'high-contrast-dark': {
    base: 'hc-black',
    inherit: true,
    rules: [
      { background: '000000' },
      { token: '', foreground: 'ffffff', background: '000000' },
      { token: 'comment', foreground: '7ca668' },
      { token: 'string', foreground: 'ce9178' },
      { token: 'keyword', foreground: '569cd6' },
      { token: 'number', foreground: 'b5cea8' },
      { token: 'type', foreground: '4ec9b0' },
      { token: 'class', foreground: '4ec9b0' },
      { token: 'function', foreground: 'dcdcaa' },
      { token: 'variable', foreground: '9cdcfe' },
      { token: 'constant', foreground: '4fc1ff' },
      { token: 'operator', foreground: 'd4d4d4' },
    ],
    colors: {
      'editor.background': '#000000',
      'editor.foreground': '#ffffff',
      'editor.selectionBackground': '#ffffff40',
      'editor.lineHighlightBackground': '#ffffff10',
      'editorCursor.foreground': '#ffffff',
    }
  },
  'high-contrast-light': {
    base: 'vs',
    inherit: true,
    rules: [
      { background: 'ffffff' },
      { token: '', foreground: '000000', background: 'ffffff' },
      { token: 'comment', foreground: '008000' },
      { token: 'string', foreground: 'a31515' },
      { token: 'keyword', foreground: '0000ff' },
      { token: 'number', foreground: '098658' },
      { token: 'type', foreground: '267f99' },
      { token: 'class', foreground: '267f99' },
      { token: 'function', foreground: '795e26' },
      { token: 'variable', foreground: '001080' },
      { token: 'constant', foreground: '0000ff' },
      { token: 'operator', foreground: '000000' },
    ],
    colors: {
      'editor.background': '#ffffff',
      'editor.foreground': '#000000',
      'editor.selectionBackground': '#00000040',
      'editor.lineHighlightBackground': '#00000010',
      'editorCursor.foreground': '#000000',
    }
  }
};

export const THEME_OPTIONS = [
  { value: 'vs-dark', label: 'VS Dark (Default)', type: 'dark', hex: '#1e1e1e' },
  { value: 'high-contrast-dark', label: 'High Contrast Dark', type: 'dark', hex: '#000000' },
  { value: 'github-dark', label: 'GitHub Dark', type: 'dark', hex: '#0d1117' },
  { value: 'dracula', label: 'Dracula', type: 'dark', hex: '#282a36' },
  { value: 'nord', label: 'Nord', type: 'dark', hex: '#2E3440' },
  { value: 'night-owl', label: 'Night Owl', type: 'dark', hex: '#011627' },
  { value: 'one-dark-pro', label: 'One Dark Pro', type: 'dark', hex: '#282c34' },
  { value: 'monokai', label: 'Monokai', type: 'dark', hex: '#272822' },
  { value: 'solarized-dark', label: 'Solarized Dark', type: 'dark', hex: '#002b36' },
  { value: 'synthwave84', label: 'SynthWave \'84', type: 'dark', hex: '#262335' },
  { value: 'vs', label: 'VS Light', type: 'light', hex: '#ffffff' },
  { value: 'high-contrast-light', label: 'High Contrast Light', type: 'light', hex: '#ffffff' },
  { value: 'github-light', label: 'GitHub Light', type: 'light', hex: '#ffffff' },
  { value: 'solarized-light', label: 'Solarized Light', type: 'light', hex: '#fdf6e3' },
];
